### PR TITLE
Rename CanonicalizeLanguageTag to CanonicalizeUnicodeLocaleId

### PR DESCRIPTION
**Pull request by jswalden**
Followup to #83 because I am a git.

### CODE REVIEW

**Comment by zbraniecki** [comment]
Did you intend to include `ResolveLocale` algo in this patch?

**Comment by jswalden** [comment]
Yes.  `ResolveLocale` includes a call of `CanonicalizeLanguageTag` in it, so that use needs to be del/insed accordingly.  (Had it been more than really just that one case, I would have put a foot down on making the editorial name-change after proposal merge.  But it's just one algorithm, it's not absolutely terrible...)

**Comment by zbraniecki** [comment]
Ah, I see! Yeah, makes sense

**Review by zbraniecki — APPROVED** [review]

**Comment by zbraniecki** [comment]
Thank you!

**Comment by jswalden** [comment]
It is perhaps worth noting that I changed _visible_ text uses, but I didn't change the sec-href or aoid uses -- the former is permalink-useful, the latter I'm guessing is roughly the same, so I left well enough alone.

**Pull request merged**
