### PR TITLE
Clarify which language subtag to return out of the language getter.

### PR DESCRIPTION
**Pull request by zbraniecki**
Fixes #77.

### CODE REVIEW

**Comment by anba** [comment]
Similar changes are also necessary for the "region" and "script" getter. And additionally in the ApplyOptionsToTag operation.

**Review by littledan — APPROVED** [review]

**Comment by zbraniecki** [comment]
@anba - can you review? I see more cases in `ApplyOptionsToTag` which may use it, but I think that they're already constrained by the prior limitations so I hope the additional specifications are not needed.

**Review by caiolima — APPROVED** [review]
LGTM.

**Comment by zbraniecki** [comment]
I'm going to merge this and we can improve further if needed.

**Comment by anba** [comment]
The wrong productions were updated in ApplyOptionsToTag.

For example step 4.a currently has:
> If language does not match the unicode_language_subtag production of the unicode_language_id, throw a RangeError exception.

But it should be:
> If language does not match the unicode_language_subtag production, throw a RangeError exception.

Same issue in steps 6.a and 8.a.

----

The ones which need to be updated are in steps 10-12.

For example step 10.b is currently:
> Set tag to tag with the substring corresponding to the unicode_language_subtag production replaced by the string language.

But per UTS 35, `unicode_language_subtag` can appear in two different productions within a `unicode_locale_id`: Either as part of `unicode_language_id` or in the `tlang` production. So step 10.b should read:
> Set tag to tag with the substring corresponding to the unicode_language_subtag production of the unicode_language_id replaced by the string language.

Same deal with the other `unicode_language_subtag`, `unicode_script_subtag`, and `unicode_region_subtag` references in steps 10-12.

**Comment by anba** [comment]
Step 5 in https://tc39.es/proposal-intl-locale/#sec-Intl.Locale.prototype.script and https://tc39.es/proposal-intl-locale/#sec-Intl.Locale.prototype.region also needs be updated:

For example instead of:
> If locale does not contain the ["-" unicode_script_subtag] sequence, return undefined.

We need something along the lines:
> If the unicode_language_id production of locale does not contain the ["-" unicode_script_subtag] sequence, return undefined.

**Pull request merged**
